package dev.cse3000.loader

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.attribute.PosixFilePermissions

/**
 * Emits a single `data.sql` containing INSERT statements in FK-dependency
 * order, plus `apply.sh` / `apply.bat` convenience scripts and a `schema.txt`
 * snapshot for sanity-checking against the .db at apply time.
 *
 * Apply with: `bash apply.sh /path/to/proposals.db` (or `apply.bat` on Windows).
 *
 * The output is a one-shot push: re-applying against a .db that already
 * contains the same project_ids' rows will fail on PRIMARY KEY violations.
 * That's intentional per the plan.
 */
class SqlWriter(private val outDir: Path) {
    fun write(rows: Rows, schemaSource: Path?) {
        Files.createDirectories(outDir)

        // Schema snapshot
        val schemaTarget = outDir.resolve("schema.sql")
        if (schemaSource != null && Files.exists(schemaSource)) {
            Files.copy(schemaSource, schemaTarget, java.nio.file.StandardCopyOption.REPLACE_EXISTING)
        } else {
            Files.writeString(schemaTarget, "-- db-schema.sql not found at loader run time\n")
        }

        // data.sql
        val sql = buildString {
            appendLine("-- Generated by :loader. Apply once to a fresh proposals.db.")
            appendLine("-- This is a one-shot push; re-apply will fail on PRIMARY KEY violations.")
            appendLine("PRAGMA foreign_keys = OFF;")
            appendLine("BEGIN TRANSACTION;")
            appendLine()
            appendProjects(rows.projects)
            appendPersons(rows.persons)
            appendOrganisations(rows.organisations)
            appendPersonUsernames(rows.personUsernames)
            appendAffiliations(rows.affiliations)
            appendProposals(rows.proposals)
            appendProposalRevisions(rows.proposalRevisions)
            appendProposalRevisionAuthors(rows.proposalRevisionAuthors)
            appendStageHistory(rows.stageHistory)
            appendRelatedProposals(rows.relatedProposals)
            appendComments(rows.comments)
            appendLine("COMMIT;")
        }
        Files.writeString(outDir.resolve("data.sql"), sql)

        Files.writeString(outDir.resolve("apply.sh"), APPLY_SH)
        Files.writeString(outDir.resolve("apply.bat"), APPLY_BAT)
        runCatching {
            Files.setPosixFilePermissions(
                outDir.resolve("apply.sh"),
                PosixFilePermissions.fromString("rwxr-xr-x"),
            )
        }
    }

    // ─── Per-table emit ────────────────────────────────────────────────────

    private fun StringBuilder.appendProjects(items: List<Project>) {
        if (items.isEmpty()) return
        appendLine("-- Project (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO Project(project_id, project_name, enhancement_proposal_name, copyright) " +
                        "VALUES (${e(it.projectId)}, ${e(it.projectName)}, ${e(it.enhancementProposalName)}, ${e(it.copyright)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendPersons(items: List<Person>) {
        if (items.isEmpty()) return
        appendLine("-- Person (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO Person(person_id, full_name) VALUES (${e(it.personId)}, ${e(it.fullName)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendOrganisations(items: List<Organisation>) {
        if (items.isEmpty()) return
        appendLine("-- Organisation (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO Organisation(organisation_id, organisation_name) " +
                        "VALUES (${e(it.organisationId)}, ${e(it.organisationName)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendPersonUsernames(items: List<PersonUsername>) {
        if (items.isEmpty()) return
        appendLine("-- PersonUsername (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO PersonUsername(person_id, domain, username, real_name) " +
                        "VALUES (${e(it.personId)}, ${e(it.domain)}, ${e(it.username)}, ${e(it.realName)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendAffiliations(items: List<Affiliation>) {
        if (items.isEmpty()) return
        appendLine("-- Affiliation (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO Affiliation(organisation_id, person_id) " +
                        "VALUES (${e(it.organisationId)}, ${e(it.personId)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendProposals(items: List<Proposal>) {
        if (items.isEmpty()) return
        appendLine("-- Proposal (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO Proposal(project_id, proposal_id, topic, proposal_type) " +
                        "VALUES (${e(it.projectId)}, ${e(it.proposalId)}, ${e(it.topic)}, ${e(it.proposalType)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendProposalRevisions(items: List<ProposalRevision>) {
        if (items.isEmpty()) return
        appendLine("-- ProposalRevision (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO ProposalRevision(project_id, proposal_id, revision_index, title, created_at, content, implemented_at_version) " +
                        "VALUES (${e(it.projectId)}, ${e(it.proposalId)}, ${e(it.revisionIndex)}, " +
                        "${e(it.title)}, ${e(it.createdAt)}, ${e(it.content)}, ${e(it.implementedAtVersion)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendProposalRevisionAuthors(items: List<ProposalRevisionAuthor>) {
        if (items.isEmpty()) return
        appendLine("-- ProposalRevisionAuthor (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO ProposalRevisionAuthor(project_id, proposal_id, revision_index, author_id) " +
                        "VALUES (${e(it.projectId)}, ${e(it.proposalId)}, ${e(it.revisionIndex)}, ${e(it.authorId)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendStageHistory(items: List<StageHistory>) {
        if (items.isEmpty()) return
        appendLine("-- StageHistory (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO StageHistory(project_id, proposal_id, status_index, normalized_status, raw_status, created_at) " +
                        "VALUES (${e(it.projectId)}, ${e(it.proposalId)}, ${e(it.stageIndex)}, " +
                        "${e(it.normalizedStatus)}, ${e(it.rawStatus)}, ${e(it.createdAt)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendRelatedProposals(items: List<RelatedProposal>) {
        if (items.isEmpty()) return
        appendLine("-- RelatedProposal (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO RelatedProposal(project_id, proposal_id, related_project_id, related_proposal_id, type) " +
                        "VALUES (${e(it.projectId)}, ${e(it.proposalId)}, ${e(it.relatedProjectId)}, " +
                        "${e(it.relatedProposalId)}, ${e(it.type)});",
            )
        }
        appendLine()
    }

    private fun StringBuilder.appendComments(items: List<Comment>) {
        if (items.isEmpty()) return
        appendLine("-- Comment (${items.size})")
        for (it in items) {
            appendLine(
                "INSERT INTO Comment(comment_id, author_id, project_id, proposal_id, comment_on_comment_id, created_at, content) " +
                        "VALUES (${e(it.commentId)}, ${e(it.authorId)}, ${e(it.projectId)}, " +
                        "${e(it.proposalId)}, ${e(it.commentOnCommentId)}, ${e(it.createdAt)}, " +
                        "${e(it.content)});",
            )
        }
        appendLine()
    }

    /** SQLite-safe value rendering. Escapes single quotes; emits NULL for nulls; numbers verbatim. */
    private fun e(v: Any?): String = when (v) {
        null -> "NULL"
        is Number -> v.toString()
        is Boolean -> if (v) "1" else "0"
        is String -> "'" + v.replace("'", "''") + "'"
        else -> "'" + v.toString().replace("'", "''") + "'"
    }

    companion object {
        private val APPLY_SH = $$"""
            #!/usr/bin/env bash
            set -euo pipefail
            DB="${1:?Usage: $0 path/to/proposals.db}"
            HERE="$(cd "$(dirname "$0")" && pwd)"
            sqlite3 "$DB" < "$HERE/data.sql"
            echo "Applied data.sql to $DB"
        """.trimIndent() + "\n"

        private val APPLY_BAT = """
            @echo off
            if "%~1"=="" (
              echo Usage: %~nx0 path\to\proposals.db
              exit /b 1
            )
            sqlite3 "%~1" < "%~dp0data.sql"
            echo Applied data.sql to %~1
        """.trimIndent() + "\n"
    }
}
